[package]
name = "sandpiles"
version = "0.3.0"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
colorgrad = "0.6.2"
plotters = "0.3.4"
rayon = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
